import enum


class UserRole(str, enum.Enum):
    OPERATOR = "OPERATOR"
    TECHNICIAN = "TECHNICIAN"
    SUPERVISOR = "SUPERVISOR"
    MANAGER = "MANAGER"


class MachineStatus(str, enum.Enum):
    RUNNING = "RUNNING"
    WARNING = "WARNING"
    DOWN = "DOWN"
    MAINTENANCE = "MAINTENANCE"


class IncidentSeverity(str, enum.Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class IncidentPriority(str, enum.Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class IncidentStatus(str, enum.Enum):
    OPEN = "OPEN"
    ASSIGNED = "ASSIGNED"
    IN_PROGRESS = "IN_PROGRESS"
    WAITING = "WAITING"
    ESCALATED = "ESCALATED"
    RESOLVED = "RESOLVED"
    APPROVED = "APPROVED"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"


class WorkOrderStatus(str, enum.Enum):
    OPEN = "OPEN"
    ASSIGNED = "ASSIGNED"
    IN_PROGRESS = "IN_PROGRESS"
    WAITING = "WAITING"
    ESCALATED = "ESCALATED"
    RESOLVED = "RESOLVED"
    APPROVED = "APPROVED"
    CLOSED = "CLOSED"


class MaintenanceFrequency(str, enum.Enum):
    DAILY = "DAILY"
    WEEKLY = "WEEKLY"
    MONTHLY = "MONTHLY"
    QUARTERLY = "QUARTERLY"
    ANNUAL = "ANNUAL"


class ApprovalStatus(str, enum.Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class DocumentType(str, enum.Enum):
    MANUAL = "MANUAL"
    SOP = "SOP"
    SAFETY = "SAFETY"
    TROUBLESHOOTING = "TROUBLESHOOTING"
    MAINTENANCE_GUIDE = "MAINTENANCE_GUIDE"
    MAINTENANCE_RECORD = "MAINTENANCE_RECORD"


class DocumentApprovalStatus(str, enum.Enum):
    DRAFT = "DRAFT"
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    ARCHIVED = "ARCHIVED"


class IndexingStatus(str, enum.Enum):
    PENDING = "PENDING"
    INDEXED = "INDEXED"
    FAILED = "FAILED"


class GroundingStatus(str, enum.Enum):
    GROUNDED = "GROUNDED"
    PARTIALLY_GROUNDED = "PARTIALLY_GROUNDED"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


class FeedbackType(str, enum.Enum):
    HELPFUL = "HELPFUL"
    NOT_HELPFUL = "NOT_HELPFUL"


class NotificationType(str, enum.Enum):
    ASSIGNMENT = "ASSIGNMENT"
    APPROVAL = "APPROVAL"
    LOW_STOCK = "LOW_STOCK"
    STATUS_CHANGE = "STATUS_CHANGE"
    ALERT = "ALERT"


class AuditAction(str, enum.Enum):
    LOGIN = "LOGIN"
    USER_CREATED = "USER_CREATED"
    USER_ROLE_CHANGED = "USER_ROLE_CHANGED"
    INCIDENT_CREATED = "INCIDENT_CREATED"
    TECHNICIAN_ASSIGNED = "TECHNICIAN_ASSIGNED"
    PRIORITY_CHANGED = "PRIORITY_CHANGED"
    WORK_STARTED = "WORK_STARTED"
    WORK_LOG_ADDED = "WORK_LOG_ADDED"
    PARTS_USED = "PARTS_USED"
    WORK_COMPLETED = "WORK_COMPLETED"
    MAINTENANCE_APPROVED = "MAINTENANCE_APPROVED"
    MAINTENANCE_REJECTED = "MAINTENANCE_REJECTED"
    PART_INVENTORY_CHANGED = "PART_INVENTORY_CHANGED"
    PART_RESTOCKED = "PART_RESTOCKED"
    DOCUMENT_UPLOADED = "DOCUMENT_UPLOADED"
    DOCUMENT_INGESTED = "DOCUMENT_INGESTED"
    SCHEDULE_CREATED = "SCHEDULE_CREATED"
    SCHEDULE_TRIGGERED = "SCHEDULE_TRIGGERED"
    AI_QUERY_EXECUTED = "AI_QUERY_EXECUTED"
    AI_FEEDBACK_RECORDED = "AI_FEEDBACK_RECORDED"

